@extends('template.main')
@section('content')
    @include('partials.all.HeaderPage')
    @include('partials.service.service')
    @include('partials.service.features')
    @include('partials.service.serviceCards')
    @include('partials.all.newsletter')
    @include('partials.all.contact')
@endsection